project:
  type: book
  output-dir: docs

book:
  title: "Databricks Free Edition Geospatial Cookbook with DuckDB"
  author: "Daniel Sparing"
  repo-url: https://github.com/danielsparing/databricks-geospatial-cookbook
  repo-actions: [edit, issue]
  sharing: [linkedin]

  chapters:
    - index.qmd
        
    - part: "Setup"
      chapters:
        - duckdb-on-databricks/DuckDB_on_Databricks.ipynb
    
    - part: "Geospatial Delta Lake"
      chapters:
        - delta/GEOMETRY_vs_GEOGRAPHY.ipynb
        - delta/GEOMETRY.ipynb
        - delta/GEOGRAPHY.ipynb
        - delta/WKB.ipynb
    
    - part: "Import/Export to other formats"
      chapters:
        - other_formats/import.ipynb
        - other_formats/export.ipynb
        
    - part: "Visualization"
      chapters:
        - viz/native.ipynb
        - viz/lonboard.ipynb
        - viz/PMTiles.ipynb
        - viz/QGIS.ipynb
    
    - part: "Spatial functions"
      chapters:
        - stfunctions/native.ipynb
        - stfunctions/duckdb.ipynb
    
    - part: "Mapmatching"
      chapters:
        - mapmatching/databricks_graphhopper.ipynb
    
    - part: "Appendix"
      chapters: 
        - appendix/databricks_ogr2ogr_parquet.ipynb
        - appendix/https_install_duckdbextension.ipynb

format:
  html:
    theme: cosmo
    code-line-numbers: true
